### ISSUE TITLE
Markdown dependency

### ISSUE THREAD

**Issue by benwilson512** [awetzel/sweet_xml#15]
Is the `devinus/markdown` dep listed in mix.exs used for anything in production? `markdown` relies on `hoedown` which has a nif, and nifs make cross compilation a greater pain when making releases.

Can `markdown` be marked `only: :dev`?

**Comment by seantanly** [comment]
If `devinus/markdown` is only used for docs generation, I would recommend using earmark because it doesn't have external dependencies such as `hoedown`.

```
{:earmark, "~> 0.1", only: :dev},
```

**Comment by benwilson512** [comment]
From an end user standpoint, he can use which ever he wants so long as it's marked :dev :)

**Comment by seantanly** [comment]
Definitely. 

I'm wondering whether there is a particular reason to chose `devinus/markdown` over `earmark`. 

If there isn't, why choose dealing with NIF whereby some contributors like myself have some problem compiling the `hoedown` dependency out of the box, and had to switch it to earmark to get things going.

**Comment by gniquil** [comment]
When I wrote the library, earmark wasn't exactly around yet (well it was, but only heard about it on some podcast as a toy thing Dave was writing to feel out Elixir :))

**Comment by seantanly** [comment]
Thanks for the explanation. :)

I saw [phoenix](https://github.com/phoenixframework/phoenix) using `earmark` for their API docs generation and I took that as it's now good enough. :)

**Comment by viniciussbs** [comment]
:+1: for replace `devinus/markdown` for `earmark` and flag it docs-only.

**Comment by awetzel** [comment]
I updated to eamark and tests doc generation, all ok thank you for the comment
