### ISSUE TITLE
&amp; split the result in two strings

### ISSUE THREAD

**Issue by steffenix** [awetzel/sweet_xml#17]
I face a problem with escaped `"` or `&` As an example I change the test input data and this is the results I get:
```
  1) test xpath with sweet_xpath as only argment (SweetXmlTest)
     test/sweet_xml_test.exs:37
     Assertion with == failed
     code: result == ['O&ne', 'Two', 'Three', 'Four', 'Five']
     lhs:  ['O', '&ne', 'Two', 'Three', 'Four', 'Five']
     rhs:  ['O&ne', 'Two', 'Three', 'Four', 'Five']
     stacktrace:
       test/sweet_xml_test.exs:48
```

**Comment by steffenix** [comment]
So it seems to be an erlang issue.
For records, my input look like
```
<Message><Body>{&quot;user&quot;:&quot;6270&quot;,&quot;country&quot;:&quot;us&quot;}</Body></Message>
<Message><Body>{&quot;driver_id&quot;:&quot;6439&quot;,&quot;country&quot;:&quot;ca&quot;}</Body></Message>
```
For record I think I will use the `el` option and reconstruct the string based on the `Message` number.

**Comment by steffenix** [comment]
Can fix it using list and joining list after

**Comment by viniciussbs** [comment]
Hi, @steffenix. If you use 's' modifier to return strings instead of char lists, does the same error occur?

**Comment by RobinClowers** [comment]
It's great there is a workaround, but this does seem like a bug to me, can we please reopen this issue?

**Comment by RobinClowers** [comment]
And yes, the same thing happens if you specify 's'.

**Comment by steffenix** [comment]
It's because of erlang behind

**Comment by stocks29** [comment]
+1
