### ISSUE TITLE
[Proposal] Add support for `transform_by` to handle complex value transformation

### ISSUE THREAD

**Issue by seantanly** [awetzel/sweet_xml#24]
This opens up the possibility to perform complex value transformation which cannot be handled simply by adding `sigil_x/2` modifiers. 

Consider the following example, which we can tag a transformation function to a sweet_xpath spec, which is applied just before `xpath` returns. In the example, we able to capitalize the `name` and return a `Range` type for `wind_speed`.

```elixir
    iex> import SweetXml
    iex> string_to_range = fn str ->
    ...>     [first, last] = str |> String.split("-", trim: true) |> Enum.map(&String.to_integer/1)
    ...>     first..last
    ...>   end
    iex> doc = "<weather><zone><name>north</name><wind-speed>5-15</wind-speed></zone></weather>"
    iex> doc
    ...> |> xpath(
    ...>      ~x"//weather/zone"l,
    ...>      name: ~x"//name/text()"s |> transform_by(&String.capitalize/1),
    ...>      wind_speed: ~x"./wind-speed/text()"s |> transform_by(string_to_range)
    ...>    )
    [%{name: "North", wind_speed: 5..15}]
```

In fact with this, we can split up the parsing code for different xml entities into separate functions and apply them to construct different nested structures as needed.

I can put up a pull request for this proposal. :)

**Comment by seantanly** [comment]
Here's an example from the pull request on how `transform_by/2` can be used to breakdown parsing code into reusable functions that can be used in nesting.

```elixir
doc = "<li><name><first>john</first><last>doe</last></name><age>30</age></li>"

parse_name = fn xpath_node ->
  xpath_node |> xmap(
    first: ~x"./first/text()"s |> transform_by(&String.capitalize/1),
    last: ~x"./last/text()"s |> transform_by(&String.capitalize/1)
  )
end

result = doc |> xpath(
  ~x"//li"l,
  name: ~x"./name" |> transform_by(parse_name),
  age: ~x"./age/text()"i
)

^result = [%{age: 30, name: %{first: "John", last: "Doe"}}]
```

**Comment by awetzel** [comment]
see #25
