### ISSUE TITLE
Get first element name

### ISSUE THREAD

**Issue by programisti** [awetzel/sweet_xml#27]
Hi Ive spent day to just catch the first element of the xml
for example how to catch "cars" from this example:

```
<cars>
  <car>
    <make>audi</make>
    <model>a4</model>
  </car>
</cars>
```

**Comment by awetzel** [comment]
Hello you : 
`parse(xml) |> xmlElement(:name)`
should do the job :)

**Comment by awetzel** [comment]
for the explanations : 
- SweetXML handles `xmlElement` records of xmerl : https://github.com/erlang/otp/blob/master/lib/xmerl/include/xmerl.hrl#L74-L86
- so if you does not use the xpath for attribute (`/@toto`) or text node (`/text()`), you actually get a "record", so a tuple with ordered file defined in the above ".hrl"
  `{:xmlElement,name,expanded_nam,xmlns_spec,ns_info,namespace,parents,
     attributes,content,language,xmlbase,elementdef}`
- to handle these macros, `SweetXml` use Elixir `defrecord` : see usage here : http://elixir-lang.org/docs/stable/elixir/Record.html#defrecord/3

So read the doc of `defrecord` to see how it can be used and why : `xmlElement(e,:name)` does what you want

**Comment by programisti** [comment]
Thank you Arnaud you helped me a lot.

**Comment by awetzel** [comment]
you re welcome

**Comment by awetzel** [comment]
To complete this issue for future reader, xmerl/sweet_xml handle most of the xpath 1.0 spec, so you can use the `name()` xpath function to get the name : 

```elixir
xpath(xml, ~x"name(/*)"s)
```
