### ISSUE TITLE
Error with Erlang 19.2 and Elixir 1.4.0

### ISSUE THREAD

**Issue by kdisneur** [awetzel/sweet_xml#43]
Hi,

We start to have the following error since we bumped our versions of Erlang and Elixir:

```
[error] Process #PID<0.212.0> raised an exception
** (CaseClauseError) no case clause matching: {:halted, []}
    (sweet_xml) lib/sweet_xml.ex:582: anonymous fn/4 in SweetXml.continuation_opts/2
    (xmerl) xmerl_scan.erl:825: :xmerl_scan.scan_misc/4
    (xmerl) xmerl_scan.erl:578: :xmerl_scan.scan_document/2
    (xmerl) xmerl_scan.erl:291: :xmerl_scan.string/2
```

The error happens when we run Elixir 1.4.0, SweetXml 0.6.4, and Erlang 19.0 or 19.2. If we run the same code on Elixir 1.3.2, SweetXml 0.6.4, and Erlang 19.0 or 19.2 it works properly.

You can find a repository reproducing the error here: https://github.com/kdisneur/sweat_xml. 
The README includes the error logs we have after trying the same script on different versions of Erlang and Elixir.

I hope the error report is clear enough and don't hesitate to ask if I can be of any help :)

Thanks

**Comment by jeanparpaillon** [comment]
The problem raises when running `mix test`

I'm working on it...

**Comment by kdisneur** [comment]
Thanks @jeanparpaillon 👍 - I hope it will be merged soon
